import { Injectable, signal } from '@angular/core';

export type AppLanguage = 'en' | 'ms';

type Dictionary = Record<string, string>;

const TRANSLATIONS: Record<AppLanguage, Dictionary> = {
  en: {
      'history.snapshot.sessionsLoaded': 'Sessions Loaded',
      'history.snapshot.currentPage': 'Current Page',
      'history.snapshot.journeyPoints': 'Journey Points',
      'history.sessions': 'Sessions',
      'history.pageOf': 'Page {{page}} of {{total}}',
      'history.page': 'Page',
      'history.of': 'of',
      'history.noSessions': 'No sessions found yet.',
      'session.active': 'Active',
      'session.ended': 'Ended',
      'history.started': 'Started',
      'history.messagesLabel': 'messages',
      'history.duration': 'Duration',
      'history.minutes': 'min',
      'history.previous': 'Previous',
      'history.next': 'Next',
    'nav.chat': 'Chat',
    'nav.recentChat': 'Recent Chat',
    'nav.report': 'Report',
    'nav.profile': 'Profile',
    'nav.login': 'Login',
    'nav.signUp': 'Sign Up',
    'nav.logout': 'Logout',
    'nav.sessionAnonymous': 'Anonymous session',
    'nav.sessionRegistered': 'Registered account',
    'nav.features': 'Features',
    'nav.howItWorks': 'How It Works',
    'nav.getStarted': 'Get Started',
    'language.current': 'as English',

    'app.offline': 'You are offline. We will reconnect automatically when the network returns.',
    'app.dismiss': 'Dismiss notification',

    'auth.welcomeBack': 'Welcome Back',
    'auth.signInJourney': 'Sign in to continue your journey',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.signIn': 'Sign In',
    'auth.continueAnonymous': 'Continue Anonymously',
    'auth.noAccount': "Don't have an account?",
    'auth.signUp': 'Sign up',
    'auth.orContinueWith': 'Or continue with',
    'auth.welcome': 'Welcome to RadAI',
    'auth.chooseOption': 'Choose how you\'d like to get started',
    'auth.secureMessage': 'Your privacy and security are our top priority. All conversations are encrypted and private.',

    'register.createAccount': 'Create Account',
    'register.startJourney': 'Start your mental wellness journey',
    'register.username': 'Username',
    'register.chooseUsername': 'Choose a username',
    'register.createPassword': 'Create a password (min 6 characters)',
    'register.confirmPassword': 'Confirm Password',
    'register.confirmPasswordPlaceholder': 'Confirm your password',
    'register.passwordMismatch': 'Passwords do not match',
    'register.createAccountBtn': 'Create Account',
    'register.haveAccount': 'Already have an account?',

    'profile.title': 'Profile & Preferences',
    'profile.subtitle': 'Manage account details and the settings used by the chat experience.',
    'profile.account': 'Account',
    'profile.fullName': 'Full Name',
    'profile.phone': 'Phone',
    'profile.avatarUrl': 'Avatar URL',
    'profile.currentEmotion': 'Current Emotional State',
    'profile.bio': 'Bio',
    'profile.preferences': 'Preferences',
    'profile.language': 'Language',
    'profile.theme': 'Theme',
    'profile.timezone': 'Timezone',
    'profile.ttsAuto': 'Auto Text-to-Speech',
    'profile.ttsAutoDesc': 'Automatically read bot replies aloud in chat',
    'profile.notifications': 'Notifications',
    'profile.notificationsDesc': 'Allow reminders and in-app notifications',
    'profile.emailNotifications': 'Email Notifications',
    'profile.emailNotificationsDesc': 'Receive updates by email',
    'profile.dataConsent': 'Data Collection Consent',
    'profile.dataConsentDesc': 'Allow anonymous analytics and improvement data',
    'profile.saveChanges': 'Save Changes',
    'profile.accountSecurity': 'Account Security',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmNewPassword': 'Confirm New Password',
    'profile.optionalPassword': 'Leave blank to keep your current password',

    'dashboard.title': 'Your Wellness Dashboard',
    'dashboard.subtitle': 'A quick view of your emotional patterns, session progress, and next best actions.',
    'dashboard.history': 'History',
    'dashboard.refresh': 'Refresh',

    'history.title': 'Session History',
    'history.subtitle': 'Browse past conversations and your emotional journey over time.',

    'reports.title': 'Reports',
    'reports.subtitle': 'Generate and review backend wellness reports for a selected date range.',
    'reports.generateReport': 'Generate Report',
    'reports.savedReports': 'Saved Reports',
    'reports.youHave': 'You have {{count}} reports',
    'reports.created': 'Created',
    'reports.severity': 'Severity',
    'reports.sessionsLabel': 'sessions',
    'reports.noReports': 'No reports have been generated yet.',
    'reports.form.type': 'Report Type',
    'reports.form.weekly': 'Weekly',
    'reports.form.monthly': 'Monthly',
    'reports.form.custom': 'Custom',
    'reports.form.startDate': 'Start Date',
    'reports.form.endDate': 'End Date',
    'reports.detailTitle': 'Report Detail',
    'reports.close': 'Close',
    'reports.type': 'Type',
    'reports.averageMood': 'Average Mood',
    'reports.generated': 'Generated',
    'reports.summary': 'Summary',
    'reports.range': 'Range',
    'reports.showRaw': 'Show raw report data',
    'reports.intensityTrend': 'Intensity Trend',
    'reports.trendExplanation': 'Higher line means stronger intensity across the selected period.',
    'reports.emotionDistribution': 'Emotion Distribution',
    'reports.noEmotionData': 'No emotion distribution data available for this range.',
    'reports.emotionalJourney': 'Emotional Journey',

    'session.backToHistory': 'Back to history',
    'session.detail': 'Session Detail',
    'session.summary': 'Session Summary',
    'session.transcript': 'Transcript',
    'session.transcriptDescription': 'View the full conversation transcript and emotion annotations for this session.',
    'session.sessionId': 'Session ID',
    'session.status': 'Status',
    'session.messages': 'Messages',
    'session.started': 'Started',
    'session.userMessages': 'User Messages',
    'session.botMessages': 'Bot Messages',
    'session.noMessages': 'No messages were recorded for this session.',
    'session.you': 'You',
    'session.botName': 'RadAI',
    'session.unknownEmotion': 'Unknown emotion',
    'session.intensity': 'intensity',
    'session.detectedEmotions': 'Detected Emotions',

    'chat.language': 'Language',
    'chat.newChat': 'New Chat',
    'chat.endSession': 'End Session',
    'chat.placeholder': 'Type your message... (Enter to send, Shift+Enter for new line)',
    'chat.connected': 'Connected',
    'chat.disconnected': 'Disconnected',
    'chat.selectCom': 'Select COM port',
    'chat.connect': 'Connect',
    'chat.disconnect': 'Disconnect',
    'chat.test': 'Test',
    'chat.more': 'More',
    'chat.openPastConversations': 'Open past conversations',
    'chat.viewGeneratedReports': 'View generated reports',
    'chat.manageAccountLanguage': 'Manage account and language',

    'common.english': 'English',
    'common.malay': 'Malay',
    'common.back': 'Back',
    
    'admin.dashboard': 'Admin Dashboard',
    'admin.totalUsers': 'Total Users',
    'admin.activeToday': 'Active Today',
    'admin.activitiesToday': 'Activities Today',
    'admin.avgEmotion': 'Avg Emotion',
    'admin.activityTrend': 'Activity Trend (Last 30 Days)',
    'admin.emotionDistribution': 'Emotion Distribution',
    'admin.activityTypes': 'Activity Types',
    'admin.intensityLevels': 'User Intensity Levels',
    'admin.topCountries': 'Top Countries',
    'admin.recentActivity': 'Recent User Activity (Last 24 Hours)',
    'admin.userManagement': 'User Management',
    'admin.timestamp': 'Timestamp',
    'admin.activityType': 'Activity Type',
    'admin.emotion': 'Emotion',
    'admin.intensity': 'Intensity',
    'admin.description': 'Description',
    'admin.ban': 'Ban',
    'admin.unban': 'Unban',
    'admin.delete': 'Delete',
    'admin.status': 'Status',
    'admin.email': 'Email',
    'admin.username': 'Username',
    'admin.roles': 'Roles',
    'admin.active': 'Active',
    'admin.banned': 'Banned',
    
    'welcome.greeting': "Good afternoon! How's your day going so far?",
    'welcome.subtext': "I am here to listen and support you. What's on your mind?",
    'feature.emotionAware': 'Emotion-aware replies',
    'feature.voicePlayback': 'Voice playback',
    'feature.privateConversation': 'Private conversation',
    'home.title': 'Your AI-Powered Mental Wellness Companion',
    'home.subtitle': 'Experience compassionate support, track your emotions, and improve your wellbeing with RadAI.',
    'home.featureTag': 'AI Powered Support',
    'home.heroCardTitle': 'Start Your Wellness Journey Today',
    'home.usersStat': 'Active Users',
    'home.satisfactionStat': 'Satisfaction Rate',
    'home.featuresTitle': 'Why Choose RadAI',
    'home.featuresSubtitle': 'Discover the features that make mental wellness support accessible and effective',
    'home.aboutTitle': 'About RadAI',
    'home.feature1.title': 'Personal Wellness Companion',
    'home.feature1.desc': 'RadAI is an AI-powered mental wellness chatbot designed to provide emotional support, guidance, and recommendations tailored to your personal wellbeing journey.',
    'home.feature2.title': 'Track Your Emotions',
    'home.feature2.desc': 'Log your daily emotions, track patterns over time, and gain insights into your emotional wellbeing with detailed reports and analytics.',
    'home.feature3.title': 'Real-Time Support',
    'home.feature3.desc': 'Get instant support anytime, anywhere. Chat with our AI companion to discuss your feelings, receive coping strategies, and get personalized recommendations.',
    'home.feature4.title': 'Private & Secure',
    'home.feature4.desc': 'Your mental health is precious. All conversations are encrypted and kept completely private. Your data is never shared with third parties.',
    'home.howTitle': 'How It Works',
    'home.howSubtitle': 'Get started in three simple steps and begin your wellness journey',
    'home.step1.title': 'Share Your Feelings',
    'home.step1.desc': 'Tell us how you\'re feeling. Describe your emotions, thoughts, and what\'s on your mind in a natural, conversational way.',
    'home.step2.title': 'Receive Support',
    'home.step2.desc': 'Our AI analyzes your input and provides empathetic, personalized guidance tailored to your specific situation.',
    'home.step3.title': 'Track Progress',
    'home.step3.desc': 'Build healthy habits and track your emotional journey over time with detailed insights and wellness reports.',
    'home.statsTitle': 'Trusted by Thousands',
    'home.statUsers': 'People Using RadAI',
    'home.statMessages': 'Supportive Messages Sent',
    'home.statSatisfaction': 'User Satisfaction',
    'home.ctaTitle': 'Ready to Improve Your Mental Wellness?',
    'home.ctaSubtitle': 'Join thousands of people who are already experiencing better emotional health with RadAI',
    'home.footerDesc': 'Your personal AI mental wellness companion. Supporting your emotional health journey.',
    'home.faqTitle': 'Everything You Need To Know',
    'home.faqSubtitle': 'Find answers to common questions about RadAI and how it can support your mental wellness journey.',
    'home.faq1.question': 'How does RadAI provide support?',
    'home.faq1.answer': 'RadAI uses advanced AI and emotion recognition to understand your feelings and provide personalized, empathetic responses. Our chatbot is trained to recognize emotional patterns and offer strategies tailored to your specific needs.',
    'home.faq2.question': 'Is my data private and secure?',
    'home.faq2.answer': 'Yes, your privacy is our top priority. All conversations are encrypted end-to-end and stored securely. We never share your data with third parties, and you have full control over your information.',
    'home.faq3.question': 'Can RadAI replace a therapist?',
    'home.faq3.answer': 'RadAI is designed to complement professional mental health support, not replace it. For serious mental health concerns, we encourage you to seek help from qualified mental health professionals.',
    'home.faq4.question': 'What languages does RadAI support?',
    'home.faq4.answer': 'Currently, RadAI supports English and Malay. We are continuously working to add more languages to serve a global audience.',
    'home.communityTitle': 'Join Our Community',
    'home.communitySubtitle': 'Connect with thousands of people on their mental wellness journey',
    'home.communityHeading': 'Be Part of Something Bigger',
    'home.communityDesc': 'Join our thriving community of users who are taking control of their mental health and emotional wellbeing. Get exclusive tips, participate in wellness challenges, and support each other on your journeys.',
    'home.communityFeature1': 'Expert Guidance',
    'home.communityFeature1Desc': 'Access curated wellness tips and evidence-based practices from mental health experts.',
    'home.communityFeature2': 'Wellness Challenges',
    'home.communityFeature2Desc': 'Participate in monthly challenges designed to boost your mental wellness and build positive habits.',
    'home.communityFeature3': 'Priority Support',
    'home.communityFeature3Desc': 'Get faster response times and exclusive support features as a community member.',
    'home.emailPlaceholder': 'Enter your email address',
    'home.subscribe': 'Subscribe',
    'home.communityMembers': 'Active Community Members',
    'home.communitySupport': 'Support Available',
    'home.communityPrivacy': 'Data Privacy',
    'home.communityUptime': 'System Uptime',
    'home.cta': 'Start chatting now or create an account to unlock full features like emotion tracking and personalized insights.',
    'welcome.trySaying': 'Try saying:',
    'how.title': 'How AI Support Works',
    'how.subtitle': 'Our platform combines advanced AI and proven well‑being methods to provide effective support.',
    'how.card1.title': 'Describe Your State',
    'how.card1.desc': 'Share your feelings, thoughts, and the situation that concerns you. Use your conversational language - AI understands context and emotional nuances.',
    'how.card2.title': 'Receive Analysis and Support',
    'how.card2.desc': 'AI instantly analyzes your situation and provides personalized advice, strategies, and exercises based on evidence-based practices.',
    'how.card3.title': 'Practice Daily',
    'how.card3.desc': 'Receive regular support, track progress, and develop emotional resilience through personalized practices.',
    'footer.product': 'Product',
    'footer.features': 'Features',
    'footer.pricing': 'Pricing',
    'footer.security': 'Security',
    'footer.company': 'Company',
    'footer.about': 'About Us',
    'footer.blog': 'Blog',
    'footer.careers': 'Careers',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact Us',
    'footer.allRights': 'All rights reserved.',
    'consent.title': 'Privacy notice:',
    'consent.body': 'Messages are processed to provide emotion-aware support. By continuing you consent to processing.',
    'consent.button': 'I understand',
    'helpline.immediateDanger': "If you're in immediate danger:",
    'tips.hide': 'Hide Tips',
    'tips.helpful': 'Helpful Suggestions',
    'tips.title': 'Helpful Suggestions',
    'chat.typing': 'RadAI is thinking...',
    'action.copy': 'Copy',
    'action.regenerate': 'Regenerate',
    'safety.active': 'Safety mode is active. If you are at immediate risk, contact emergency support now.',
    'quick.breathe': 'Breathe',
    'quick.ground': 'Grounding',
    'quick.journal': 'Journal Prompt',
    'quick.goal': 'Set Goal'
    ,
    'chat.subtitle': 'Your Mental Health Companion',
    'chat.aria.openSidePanel': 'Open side panel',
    'chat.aria.newChat': 'Start a new chat',
    'chat.aria.endSession': 'End current session',
    'chat.listen': 'Listen',
    'chat.aria.readAloud': 'Read message aloud',
    'action.copyTitle': 'Copy message',
    'action.regenerateTitle': 'Generate a new response',
    'chat.intensity': 'intensity',
    'chat.aria.conversationMessages': 'Conversation messages',
    'chat.retry': 'Retry',
    'chat.aria.typeMessage': 'Type your message',
  },
  ms: {
      'history.snapshot.sessionsLoaded': 'Sesi Dimuatkan',
      'history.snapshot.currentPage': 'Halaman Semasa',
      'history.snapshot.journeyPoints': 'Titik Perjalanan',
      'history.sessions': 'Sesi',
      'history.pageOf': 'Halaman {{page}} daripada {{total}}',
      'history.page': 'Halaman',
      'history.of': 'daripada',
      'history.noSessions': 'Tiada sesi dijumpai lagi.',
      'session.active': 'Aktif',
      'session.ended': 'Berakhir',
      'history.started': 'Dimulakan',
      'history.messagesLabel': 'mesej',
      'history.duration': 'Tempoh',
      'history.minutes': 'min',
      'history.previous': 'Sebelumnya',
      'history.next': 'Seterusnya',
    'nav.chat': 'Sembang',
    'nav.recentChat': 'Sembang Terkini',
    'nav.report': 'Laporan',
    'nav.profile': 'Profil',
    'nav.login': 'Log Masuk',
    'nav.signUp': 'Daftar',
    'nav.logout': 'Log Keluar',
    'nav.sessionAnonymous': 'Sesi tanpa nama',
    'nav.sessionRegistered': 'Akaun berdaftar',
    'nav.features': 'Ciri-ciri',
    'nav.howItWorks': 'Cara Ia Berfungsi',
    'nav.getStarted': 'Mula',
    'language.current': 'dalam Bahasa Melayu',

    'app.offline': 'Anda berada di luar talian. Kami akan sambung semula secara automatik apabila rangkaian kembali.',
    'app.dismiss': 'Tutup notifikasi',

    'auth.welcomeBack': 'Selamat Kembali',
    'auth.signInJourney': 'Log masuk untuk meneruskan perjalanan anda',
    'auth.email': 'E-mel',
    'auth.password': 'Kata Laluan',
    'auth.enterEmail': 'Masukkan e-mel anda',
    'auth.enterPassword': 'Masukkan kata laluan anda',
    'auth.signIn': 'Log Masuk',
    'auth.continueAnonymous': 'Teruskan Secara Tanpa Nama',
    'auth.noAccount': 'Belum ada akaun?',
    'auth.signUp': 'Daftar',
    'auth.orContinueWith': 'Atau teruskan dengan',
    'auth.welcome': 'Selamat Datang ke RadAI',
    'auth.chooseOption': 'Pilih cara anda ingin bermula',
    'auth.secureMessage': 'Privasi dan keselamatan anda adalah prioritas utama kami. Semua perbualan disulitkan dan peribadi.',

    'register.createAccount': 'Cipta Akaun',
    'register.startJourney': 'Mulakan perjalanan kesejahteraan mental anda',
    'register.username': 'Nama Pengguna',
    'register.chooseUsername': 'Pilih nama pengguna',
    'register.createPassword': 'Cipta kata laluan (min 6 aksara)',
    'register.confirmPassword': 'Sahkan Kata Laluan',
    'register.confirmPasswordPlaceholder': 'Sahkan kata laluan anda',
    'register.passwordMismatch': 'Kata laluan tidak sepadan',
    'register.createAccountBtn': 'Cipta Akaun',
    'register.haveAccount': 'Sudah ada akaun?',

    'profile.title': 'Profil & Keutamaan',
    'profile.subtitle': 'Urus butiran akaun dan tetapan untuk pengalaman sembang.',
    'profile.account': 'Akaun',
    'profile.fullName': 'Nama Penuh',
    'profile.phone': 'Telefon',
    'profile.avatarUrl': 'URL Avatar',
    'profile.currentEmotion': 'Emosi Semasa',
    'profile.bio': 'Bio',
    'profile.preferences': 'Keutamaan',
    'profile.language': 'Bahasa',
    'profile.theme': 'Tema',
    'profile.timezone': 'Zon Masa',
    'profile.ttsAuto': 'Auto Teks-ke-Pertuturan',
    'profile.ttsAutoDesc': 'Baca balasan bot secara automatik dalam sembang',
    'profile.notifications': 'Notifikasi',
    'profile.notificationsDesc': 'Benarkan peringatan dan notifikasi dalam aplikasi',
    'profile.emailNotifications': 'Notifikasi E-mel',
    'profile.emailNotificationsDesc': 'Terima kemas kini melalui e-mel',
    'profile.dataConsent': 'Persetujuan Pengumpulan Data',
    'profile.dataConsentDesc': 'Benarkan analitik tanpa nama untuk penambahbaikan',
    'profile.saveChanges': 'Simpan Perubahan',
    'profile.accountSecurity': 'Keselamatan Akaun',
    'profile.currentPassword': 'Kata Laluan Semasa',
    'profile.newPassword': 'Kata Laluan Baharu',
    'profile.confirmNewPassword': 'Sahkan Kata Laluan Baharu',
    'profile.optionalPassword': 'Biarkan kosong jika tidak mahu ubah kata laluan',

    'dashboard.title': 'Papan Pemuka Kesejahteraan Anda',
    'dashboard.subtitle': 'Paparan ringkas corak emosi, kemajuan sesi, dan langkah seterusnya.',
    'dashboard.history': 'Sejarah',
    'dashboard.refresh': 'Muat Semula',

    'history.title': 'Sejarah Sesi',
    'history.subtitle': 'Semak perbualan lalu dan perjalanan emosi anda dari semasa ke semasa.',

    'reports.title': 'Laporan',
    'reports.subtitle': 'Jana dan semak laporan kesejahteraan untuk julat tarikh dipilih.',
    'reports.generateReport': 'Jana Laporan',
    'reports.savedReports': 'Laporan Tersimpan',
    'reports.youHave': 'Anda mempunyai {{count}} laporan',
    'reports.created': 'Dicipta',
    'reports.severity': 'Tahap',
    'reports.sessionsLabel': 'sesi',
    'reports.noReports': 'Tiada laporan dijana lagi.',
    'reports.form.type': 'Jenis Laporan',
    'reports.form.weekly': 'Mingguan',
    'reports.form.monthly': 'Bulanan',
    'reports.form.custom': 'Tersuai',
    'reports.form.startDate': 'Tarikh Mula',
    'reports.form.endDate': 'Tarikh Tamat',
    'reports.detailTitle': 'Butiran Laporan',
    'reports.close': 'Tutup',
    'reports.type': 'Jenis',
    'reports.averageMood': 'Purata Mood',
    'reports.generated': 'Dijana',
    'reports.summary': 'Ringkasan',
    'reports.range': 'Julat',
    'reports.showRaw': 'Tunjukkan data laporan mentah',
    'reports.intensityTrend': 'Trend Intensiti',
    'reports.trendExplanation': 'Garis yang lebih tinggi bermaksud intensiti lebih kuat sepanjang tempoh yang dipilih.',
    'reports.emotionDistribution': 'Taburan Emosi',
    'reports.noEmotionData': 'Tiada data taburan emosi untuk julat ini.',
    'reports.emotionalJourney': 'Perjalanan Emosi',

    'session.backToHistory': 'Kembali ke sejarah',
    'session.detail': 'Butiran Sesi',
    'session.summary': 'Ringkasan Sesi',
    'session.transcript': 'Transkrip',
    'session.transcriptDescription': 'Lihat transkrip penuh perbualan dan anotasi emosi untuk sesi ini.',
    'session.sessionId': 'ID Sesi',
    'session.status': 'Status',
    'session.messages': 'Mesej',
    'session.started': 'Dimulakan',
    'session.userMessages': 'Mesej Pengguna',
    'session.botMessages': 'Mesej Bot',
    'session.noMessages': 'Tiada mesej direkodkan untuk sesi ini.',
    'session.you': 'Anda',
    'session.botName': 'RadAI',
    'session.unknownEmotion': 'Emosi tidak diketahui',
    'session.intensity': 'intensiti',
    'session.detectedEmotions': 'Emosi Dikesan',

    'chat.language': 'Bahasa',
    'chat.newChat': 'Sembang Baharu',
    'chat.endSession': 'Tamatkan Sesi',
    'chat.placeholder': 'Taip mesej anda... (Enter untuk hantar, Shift+Enter untuk baris baru)',
    'chat.connected': 'Bersambung',
    'chat.disconnected': 'Terputus',
    'chat.selectCom': 'Pilih port COM',
    'chat.connect': 'Sambung',
    'chat.disconnect': 'Putuskan',
    'chat.test': 'Uji',
    'chat.more': 'Lagi',
    'chat.openPastConversations': 'Buka perbualan lepas',
    'chat.viewGeneratedReports': 'Lihat laporan yang dijana',
    'chat.manageAccountLanguage': 'Urus akaun dan bahasa',

    'common.english': 'Inggeris',
    'common.malay': 'Melayu',
    'common.back': 'Kembali',
    
    'admin.dashboard': 'Papan Pemuka Admin',
    'admin.totalUsers': 'Jumlah Pengguna',
    'admin.activeToday': 'Aktif Hari Ini',
    'admin.activitiesToday': 'Aktiviti Hari Ini',
    'admin.avgEmotion': 'Purata Emosi',
    'admin.activityTrend': 'Trend Aktiviti (30 Hari Terakhir)',
    'admin.emotionDistribution': 'Taburan Emosi',
    'admin.activityTypes': 'Jenis Aktiviti',
    'admin.intensityLevels': 'Tahap Intensiti Pengguna',
    'admin.topCountries': 'Negara Teratas',
    'admin.recentActivity': 'Aktiviti Pengguna Terkini (24 Jam Terakhir)',
    'admin.userManagement': 'Pengurusan Pengguna',
    'admin.timestamp': 'Waktu',
    'admin.activityType': 'Jenis Aktiviti',
    'admin.emotion': 'Emosi',
    'admin.intensity': 'Intensiti',
    'admin.description': 'Penerangan',
    'admin.ban': 'Larang',
    'admin.unban': 'Buka Larangan',
    'admin.delete': 'Padam',
    'admin.status': 'Status',
    'admin.email': 'E-mel',
    'admin.username': 'Nama Pengguna',
    'admin.roles': 'Peranan',
    'admin.active': 'Aktif',
    'admin.banned': 'Dilarang',
    
    'welcome.greeting': 'Selamat petang! Bagaimana hari anda setakat ini?',
    'welcome.subtext': 'Saya di sini untuk mendengar dan menyokong anda. Apa yang bermain di fikiran anda?',
    'feature.emotionAware': 'Balasan peka emosi',
    'feature.voicePlayback': 'Main suara',
    'feature.privateConversation': 'Perbualan peribadi',
    'home.title': 'Teman Kesejahteraan Mental anda yang Dikuasakan oleh AI',
    'home.subtitle': 'Rasakan sokongan yang berbelas kasihan, jejak emosi anda, dan tingkatkan kesejahteraan anda dengan RadAI.',
    'home.featureTag': 'Sokongan Dikuasakan AI',
    'home.heroCardTitle': 'Mulakan Perjalanan Kesejahteraan Anda Hari Ini',
    'home.usersStat': 'Pengguna Aktif',
    'home.satisfactionStat': 'Kadar Kepuasan',
    'home.featuresTitle': 'Mengapa Pilih RadAI',
    'home.featuresSubtitle': 'Temui ciri-ciri yang menjadikan sokongan kesejahteraan mental mudah diakses dan berkesan',
    'home.aboutTitle': 'Mengenai RadAI',
    'home.feature1.title': 'Teman Kesejahteraan Peribadi',
    'home.feature1.desc': 'RadAI ialah chatbot kesejahteraan mental yang dikuasakan oleh AI untuk menyediakan sokongan emosi, panduan dan cadangan yang disesuaikan dengan perjalanan kesejahteraan anda.',
    'home.feature2.title': 'Jejak Emosi Anda',
    'home.feature2.desc': 'Catat emosi harian anda, jejak corak dari masa ke masa, dan dapatkan wawasan tentang kesejahteraan emosi anda dengan laporan dan analitik terperinci.',
    'home.feature3.title': 'Sokongan Masa Nyata',
    'home.feature3.desc': 'Dapatkan sokongan segera bila-bila masa, di mana sahaja. Bual dengan teman AI kami untuk membincangkan perasaan anda, menerima strategi pemulihan, dan cadangan yang diperibadikan.',
    'home.feature4.title': 'Peribadi & Selamat',
    'home.feature4.desc': 'Kesejahteraan mental anda amat berharga. Semua perbualan disulitkan dan disimpan dengan selamat. Data anda tidak dikongsi dengan pihak ketiga.',
    'home.howTitle': 'Bagaimana Ia Berfungsi',
    'home.howSubtitle': 'Bermula dalam tiga langkah mudah dan mulakan perjalanan kesejahteraan anda',
    'home.step1.title': 'Berkongsi Perasaan Anda',
    'home.step1.desc': 'Beritahu kami bagaimana anda berasa. Terangkan emosi, pemikiran dan perkara yang ada di fikiran anda dengan cara yang semula jadi dan mudah dipertuturkan.',
    'home.step2.title': 'Terima Sokongan',
    'home.step2.desc': 'AI kami menganalisis input anda dan memberikan panduan yang empati dan diperibadikan berdasarkan situasi khusus anda.',
    'home.step3.title': 'Jejak Kemajuan',
    'home.step3.desc': 'Bina tabiat sihat dan jejak perjalanan emosi anda dari masa ke masa dengan wawasan terperinci dan laporan kesejahteraan.',
    'home.statsTitle': 'Dipercayai oleh Ribuan',
    'home.statUsers': 'Orang Menggunakan RadAI',
    'home.statMessages': 'Mesej Sokongan Dihantar',
    'home.statSatisfaction': 'Kepuasan Pengguna',
    'home.ctaTitle': 'Bersedia untuk Meningkatkan Kesejahteraan Mental Anda?',
    'home.ctaSubtitle': 'Sertai ribuan orang yang sudah mengalami kesihatan emosi yang lebih baik dengan RadAI',
    'home.footerDesc': 'Teman AI kesejahteraan mental peribadi anda. Menyokong perjalanan kesehatan emosi anda.',
    'home.faqTitle': 'Semua Yang Anda Perlu Tahu',
    'home.faqSubtitle': 'Cari jawapan kepada soalan umum tentang RadAI dan bagaimana ia boleh menyokong perjalanan kesejahteraan mental anda.',
    'home.faq1.question': 'Bagaimana RadAI memberikan sokongan?',
    'home.faq1.answer': 'RadAI menggunakan AI canggih dan pengiktirafan emosi untuk memahami perasaan anda dan memberikan respons yang empati dan diperibadikan. Chatbot kami dilatih untuk mengenali corak emosi dan menawarkan strategi yang disesuaikan dengan kebutuhan khusus anda.',
    'home.faq2.question': 'Adakah data saya peribadi dan selamat?',
    'home.faq2.answer': 'Ya, privasi anda adalah prioritas utama kami. Semua perbualan disulitkan hujung-ke-hujung dan disimpan dengan selamat. Kami tidak pernah berkongsi data anda dengan pihak ketiga, dan anda mempunyai kawalan penuh atas maklumat anda.',
    'home.faq3.question': 'Bolehkah RadAI menggantikan seorang ahli terapi?',
    'home.faq3.answer': 'RadAI dirancang untuk melengkapi sokongan kesihatan mental profesional, bukan menggantikannya. Untuk kebimbangan kesihatan mental yang serius, kami menggalakkan anda mencari bantuan daripada profesional kesihatan mental yang berkelayakan.',
    'home.faq4.question': 'Bahasa apa yang disokong oleh RadAI?',
    'home.faq4.answer': 'Pada masa ini, RadAI menyokong Bahasa Inggeris dan Melayu. Kami terus bekerja untuk menambah lebih banyak bahasa untuk melayani khalayak global.',
    'home.communityTitle': 'Sertai Komuniti Kami',
    'home.communitySubtitle': 'Berhubung dengan ribuan orang dalam perjalanan kesejahteraan mental mereka',
    'home.communityHeading': 'Menjadi Bahagian dari Sesuatu yang Lebih Besar',
    'home.communityDesc': 'Sertai komuniti kami yang berkembang pesat dari pengguna yang mengambil kawal kesihatan mental dan kesejahteraan emosi mereka. Dapatkan tip kesejahteraan eksklusif, sertai cabaran kesejahteraan, dan sokong satu sama lain dalam perjalanan anda.',
    'home.communityFeature1': 'Panduan Pakar',
    'home.communityFeature1Desc': 'Akses tip kesejahteraan yang dikurasi dan amalan berasaskan bukti daripada pakar kesihatan mental.',
    'home.communityFeature2': 'Cabaran Kesejahteraan',
    'home.communityFeature2Desc': 'Sertai cabaran bulanan yang dirancang untuk meningkatkan kesejahteraan mental anda dan membina tabiat positif.',
    'home.communityFeature3': 'Sokongan Keutamaan',
    'home.communityFeature3Desc': 'Dapatkan masa respons yang lebih cepat dan ciri sokongan eksklusif sebagai ahli komuniti.',
    'home.emailPlaceholder': 'Masukkan alamat e-mel anda',
    'home.subscribe': 'Langgan',
    'home.communityMembers': 'Ahli Komuniti Aktif',
    'home.communitySupport': 'Sokongan Tersedia',
    'home.communityPrivacy': 'Privasi Data',
    'home.communityUptime': 'Uptime Sistem',
    'home.cta': 'Mula sembang sekarang atau cipta akaun untuk membuka ciri penuh seperti penjejakan emosi dan wawasan yang diperibadikan.',
    'welcome.trySaying': 'Cuba katakan:',
    'how.title': 'Bagaimana Sokongan AI Berfungsi',
    'how.subtitle': 'Platform kami menggabungkan AI maju dan kaedah kesejahteraan yang terbukti untuk menyediakan sokongan yang berkesan.',
    'how.card1.title': 'Terangkan Keadaan Anda',
    'how.card1.desc': 'Kongsikan perasaan, pemikiran dan situasi yang membimbangkan anda. Gunakan bahasa perbualan anda - AI memahami konteks dan nuansa emosi.',
    'how.card2.title': 'Terima Analisis dan Sokongan',
    'how.card2.desc': 'AI menganalisis situasi anda dengan segera dan menyediakan nasihat peribadi, strategi dan latihan berdasarkan amalan berasaskan bukti.',
    'how.card3.title': 'Amalkan Setiap Hari',
    'how.card3.desc': 'Terima sokongan secara berkala, jejak kemajuan, dan bangunkan daya tahan emosi melalui amalan yang diperibadikan.',
    'consent.title': 'Pemberitahuan privasi:',
    'consent.body': 'Mesej diproses untuk menyediakan sokongan peka emosi. Dengan meneruskan anda bersetuju dengan pemprosesan.',
    'consent.button': 'Saya faham',
    'helpline.immediateDanger': 'Jika anda dalam bahaya segera:',
    'tips.hide': 'Sembunyikan Petua',
    'tips.helpful': 'Cadangan Berguna',
    'tips.title': 'Cadangan Berguna',
    'chat.typing': 'RadAI sedang berfikir...',
    'action.copy': 'Salin',
    'action.regenerate': 'Jana semula',
    'safety.active': 'Mod keselamatan diaktifkan. Jika anda berisiko segera, hubungi sokongan kecemasan sekarang.',
    'quick.breathe': 'Tarik Nafas',
    'quick.ground': 'Pembumian',
    'quick.journal': 'Arahan Jurnal',
    'quick.goal': 'Tetapkan Matlamat'
    ,
    'chat.subtitle': 'Teman Kesihatan Mental Anda',
    'chat.aria.openSidePanel': 'Buka panel sisi',
    'chat.aria.newChat': 'Mula sembang baru',
    'chat.aria.endSession': 'Tamatkan sesi semasa',
    'chat.listen': 'Dengar',
    'chat.aria.readAloud': 'Baca mesej dengan kuat',
    'action.copyTitle': 'Salin mesej',
    'action.regenerateTitle': 'Jana semula respons',
    'chat.intensity': 'intensiti',
    'chat.aria.conversationMessages': 'Mesej perbualan',
    'chat.retry': 'Cuba semula',
    'chat.aria.typeMessage': 'Taip mesej anda',
  }
};

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private readonly STORAGE_KEY = 'radai_language';
  private readonly _language = signal<AppLanguage>('en');

  readonly language = this._language.asReadonly();

  constructor() {
    const stored = localStorage.getItem(this.STORAGE_KEY);
    this.setLanguage(stored === 'ms' ? 'ms' : 'en');
  }

  setLanguage(language: AppLanguage): void {
    this._language.set(language);
    localStorage.setItem(this.STORAGE_KEY, language);
    document.documentElement.lang = language;
  }

  t(key: string): string {
    const lang = this._language();
    return TRANSLATIONS[lang][key] || TRANSLATIONS.en[key] || key;
  }
}
